rackerlabs/support-how-to

- content/how-to/cloud-servers/_index.md
For missing redirects or cases where the permalink and folder name do not match.
> Fixing links

- content/how-to/_index.md
- content/how-to/rms-cloudflare/_index.md
- content/how-to/rms-cloudflare/cloudflare-supported-features/index.md
- content/how-to/rms-cloudflare/how-cloudflare-works/index.md
- content/how-to/rms-cloudflare/rms-cloudflare-all-articles/index.md
- content/how-to/rms-cloudflare/rms-cloudflare-faq/index.md
- content/how-to/rms-cloudflare/understanding-bot-management/index.md
Change "Cloudflare Edge Security Solutions" to "Cloudflare with Rackspace Managed Services" for all Cloudflare articles.
> update cloudflare service name

- content/how-to/cloud-servers/using-ntp-to-sync-time/index.md
JIRA 6344
full audit for Use NTP to sync time
> apply sme feedback for audit

- content/how-to/rackspace-monitoring/rackspace-monitoring-faq/index.md
removing a link to a blog that was archived and has no appropriate replacement
> remove dead link

- content/how-to/rackspace-monitoring/mobile-alerts-from-rackspace-monitoring/index.md
Removing a link to a Rackspace blog that no longer exists
> remove outdated link

- content/how-to/office-365/add-a-domain-in-office-365/index.md
> fix malformed link pt 2

- content/how-to/office-365/configure-dns-for-office-365-services/index.md
one of the links was malformed, so this PR fixes it
> fix malformed link

- content/how-to/cloud-servers/configure-mysql-server-on-the-ubuntu-operating-system/index.md
- content/how-to/cloud-servers/install-mysql-server-on-the-ubuntu-operating-system/index.md
- content/how-to/cloud-servers/reset-a-mysql-root-password/index.md
> fix broken link

- content/how-to/cloud-servers/using-task-states-with-server-imaging/index.md
JIRA 6108
SME feedback was that the article looked good, but one link was broken, so I've updated the link to point to the correct URL for the article.
> update link to resource article

- content/how-to/exchange/manage-public-folders-in-the-control-panel-for-hosted-exchange-2007-and-2010/index.md
fix https://github.com/rackerlabs/support-how-to/issues/321
> fix format

- content/how-to/cloud-servers/list-cloud-monitoring-zones-with-pitchfork/index.md
referencing Fix broken link #3933 on old repo
> broken link

- content/how-to/cloud-servers/migrate-a-cloud-server-to-a-new-physical-host/index.md
this article was left behind during the migration, so bringing it over now
> add article that was lost in the move

- content/how-to/rackspace-email/set-up-dns-records-for-cloud-office-email/index.md
This commit changes first appearance of DNS to Domain Name System(DNS) and includes missing commas in conditional sentences.
> Corrects punctuation errors

- content/how-to/cloud-servers/install-python-novaclient-on-windows/index.md
> Minor changes

- content/how-to/cloud-servers/installing-fwbuilder/index.md
Could you please review and edit @stephamon ?
> Minor Style changes

- content/how-to/cloud-servers/high-level-steps-for-migrating-from-amazon-web-services/index.md
JIRA 6035
SME confirmed this is all still correct.
> add audit date

- content/how-to/cloud-servers/testing-network-services-with-netcat/index.md
Halfway through edit, started testing and noticed that the creator has not updated or maintained the software since 2006. I suspect this is a candidate for retirement. Could you help me with this @stephamon?
> Retirement Candidate and structural edits

- content/how-to/general/lon7-global-switch-data-center-migration-faq-for-managed-customers/index.md
per Annabelle Dhanani <Annabelle.Dhanani@rackspace.com>
> update move date

- content/how-to/managed-operations/managed-operations-faq/index.md
section has been removed as it no longer applies
> removed section

- content/how-to/cloud-block-storage/minimizing-the-impact-of-cloud-block-storage-maintenance/index.md
Adding a few steps for what to do after a maintenance has completed.
> Cbs maint updates

- Makefile
- netlify.toml
- Enable code in `layouts/partials/head.html` to control robots.txt
- Bump to latest Hugo version
> Set HUGO_ENV; Bump Hugo version

- content/how-to/cloud-servers/ensure-servers-reboot-successfully/index.md
Hi! @catlook Would you please review:edit this article? Thank you!
> attempts to eliminate passive voice

- content/how-to/cloud-servers/learn-more-about-cloud-servers/index.md
Hi! Could you please review:edit this when you have a chance? Thank you!
> changes last modified date

- content/how-to/cloud-dns/choosing-dns-record-types/index.md
Hi @catlook ! Could you please review:edit this when you have a chance? Thank you soo much!
> small changes in style

- content/how-to/office-365/add-an-office-365-license/index.md
Reflects a naming change made in the Office 365 Control Panel.
> Product Catalog --> Business Catalog

- content/how-to/cloud-servers/terms-of-service/index.md
Hi! @catlook Could you please review:edit this when you have a chance? It just updates audit and last modified dates
> Updates audit and last modified dates

- content/how-to/cloud-servers/migrate-a-cloud-server-to-a-new-physical-host/index.md
Note: For the purposes of submitting the change, I have added a # to line 58 to show the dead link location. 
This article has a dead link. I'm not sure what to change to make this link work again, but the correct page it needs to link to is:
https://docs.rackspace.com/support/how-to/ensure-servers-reboot-successfully/
> Fix Dead Link

- content/how-to/cloud-servers/installing-ftp-on-windows-server-2012-r2/index.md
- content/how-to/cloud-servers/log-in-to-your-server-via-rdp-windows/index.md
JIRA 6569 and 6571
SME verified the articles and provided an updated link
> SME feedback and edits for full audits

- content/how-to/cloud-servers/investigate-compromised-servers/index.md
> fix index.md compromised-servers

- archetypes/support-bundle/concept-based-article-template.md
- archetypes/support-bundle/task-based-article-template.md
- archetypes/support-bundle/troubleshooting-article-template.md
Bring in the template files from the legacy repo.
These templates need additional work for new repo.
> Add template files

- layouts/partials/head.html
The qualtrics intercept had to be recreated after the account migration, so this PR is updating the script to the new intercept.
> update qualtrics script for new intercept

- content/how-to/dedicated-hosting/remediation-of-cve-2020-1472-netlogon-elevation-of-privilege-vulnerability/index.md
FIx link to point properly at MS documentation
> update link to microsoft

- content/how-to/account-management/combine-invoices-for-rackspace-managed-and-cloud-accounts/index.md
JIRA 6354
Apply CBUI changes to the instructions and update the language around account types.
> update instructions for CBUI changes - merge Dec or Jan

- content/how-to/rackspace-email/factors-that-affect-the-duration-of-email-migrations/index.md
Hi! Could you please review&edit this? Thank you!!!
> factors that affect email migration duration

- content/how-to/retired-articles/cloud-servers-with-managed-operations-support-for-linux/index.md
- static/_redirects
I found this article while trawling our how-to website. Initially couldn't find it the content folder. Found it in the "retired" folder. I'm making sure it's retired.
> retires article

- script/audits.py
- script/find-mismatches.sh
- script/lastupdate.sh
- script/newfiles-by-gts.sh
- script/newfiles.sh
- script/no-audits.py
restoring the scripts that mysteriously disappeared
> bring back scripts folder

- .github/dependabot.yml
> Add Dependabot automated security update bot

- CONTRIBUTING.md
added and refined steps so that contributors know how to contribute.
> updates to steps and procedures

- content/how-to/cloud-servers/migrations-in-rackspace-cloud/index.md
New article covering some FAQs about Live Migrations. Since Live Migrations are meant to be non-impacting, we'd like to have a document that customers can view when the live migration is unsuccessful and requires a reboot migration.
> Create new article about live migrations

- content/how-to/cloud-backup/update-or-install-the-cloud-backup-agent-on-linux/index.md
> correction on line 33

- content/how-to/cloud-servers/migrations-in-the-rackspace-cloud/index.md
Hi @catlook ! Could you please review this PR? It was recently edited by Steph , but I didn't notice the file name and the permalink were slightly different.  I created this to fix that.
> Change file name to match permalink

- static/_redirects
Hi @catlook ! Could you please take a look at this redirect and see if it looks right to you? Thank you!
> Redirects Migrations in Rackspace Cloud to right link

- content/how-to/cloud-servers/list-cloud-monitoring-zones-with-pitchfork/index.md
Article was missing the "last modified date" and "last modified by" in the metadata and also had an audit date set before the article was created. I used the commit history of the article to find the proper dates.
> add last modified date

- content/how-to/cloud-servers/centos-7-apache-and-php-install/index.md
Hi @catlook ! Could you please review and edit this article? It has already been revised by the CentOS SME. Thank you!
> Audit article: CentOS 7 Apache and PHP install

- content/how-to/cloud-backup/migrating-the-cloud-backup-vault/index.md
Line  21 appears to have an issue with the header not showing up. 
I'm not sure what needs to change in markup to make that happen since it appears to be formatted correctly. 
Can this be fixed?
> Fix missing header

- static/_redirects
Hi @catlook ! These are the redirects I've created after merging the three "Shut down a Rackspace Cloud Server articles".
Could you please take a look at this PR and give me your ok? Thank you
> Redirects, dependency of PR 803 -merging three redundant articles

- static/_redirects
Hi @stephamon  Could you please review this PR? It's a redirect concerning one of the broken links Brad Dumpleton reported. I'm going to fix it little by little, depending on the links I can find.
> Redirect one of the broken links in Cloud Portal

- static/_redirects
Hi @stephamon Could you please review this PR? It contains the Cloud Portal redirects. Thank you
> Fix broken Cloud Portal links

- content/how-to/rackspace-pdr/rackspace-pdr-agent-networking/index.md
Removed R7/AL and added Armor requirements.
> Updated PDRv1 to V2

- content/how-to/rackspace-pdr/rackspace-pdr-imaging/index.md
> Updated the article

- content/how-to/rackspace-email/spam-preferences-safelists-and-blocklist-in-rackspace-email/index.md
Hi @catlook Could you please review and edit this PR when you have a chance? Thank you =)
> Updates previous article per SME's request. SME provided changes

- content/how-to/rackspace-email/adding-an-alias-with-rackspace-email/index.md
Hi @catlook ! Could you please review and edit this PR? I updated it per the SME's request, who, by the way, provided the changes.  Thank you =)
> Updates previous articles per SME's request. SME provided the changes

- content/how-to/cloud-servers/creating-and-deleting-local-users-on-windows-server/index.md
Hi @catlook ! Could you review and edit this PR when you have a chance? Thank you =)
> Audit article: Creating and deleting local users on Windows

- content/how-to/cloud-servers/private-cloud-is-rad-how-to-leverage-private-cloud-for-rapid-application-development/index.md
Hi @catlook Could you review and edit this PR when you have a chance? Thank you =)
> Audit article: Private Cloud is RAD

- content/how-to/rackspace-email/email-everyone-cloud-office-control-panel/index.md
Hi @catlook Could you please review and edit this PR? The changes were requested by the SME.
> Audit article: Email everyone in a domain: Cloud office control panel

- content/how-to/rackspace-email/domains-cloud-office-control-panel/index.md
Hi @catlook Could you please review and edit this PR? It has already been approved by the SME. Thank you
> Audit article: SME reviewed it and approved, added CTA

- content/how-to/rackspace-email/set-up-spf-and-dkim-records/index.md
Hi @catlook ! Could you please review and edit this PR when you have a chance? I changed the linked articles. Thank you.
> Audit article: Set up SPF and DKIM records, changed linked articles per SME

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Operating Systems were EOL on 11/30/2020
> Remove Cent OS6/RHEL 6

- content/how-to/cloud-servers/migrate-a-cloud-server-to-a-new-physical-host/index.md
Added a small blurb at the bottom of the article to instruct customers how to confirm the migration completed in the portal.
> Add Confirm Resize information

- content/how-to/cloud-servers/plesk-introduction/index.md
Typo.  Has "sring" instead of "string"
> Update to string

- content/how-to/cloud-servers/plesk-ssl-installation/index.md
Has "SecureShell" but an SSL is a "Secure Sockets Layer"
> Update from SecureShell

- content/how-to/account-management/reasonable-endeavors-billable-services-for-linux/index.md
> create reasonable endeavors article

- content/how-to/cloud-block-storage/attach-a-cloud-block-storage-volume-to-an-onmetal-server-through-the-cloud-control-panel/index.md
Hi @catlook Could you please review and edit this PR when you have a chance? Thank you
> Audit article: Attach a cloud block storage volume -changes per SME

- content/how-to/rackspace-email/webmail-dropbox-integration-faqs/index.md
Hi @catlook Could you please review and edit this PR when you have a chance? Tomorrow's fine, it's not urgent. =) Thank you
> Audit article: Webmail Dropbox integration faqs per SME

- content/how-to/cloud-backup/migrating-the-cloud-backup-vault/index.md
Feedback from another Racker regarding the original wording in this section. 
The original wording was a bit strange so I changed it to clear it up a bit.
> Update Cloud Backup Vault Migration Article

- content/how-to/rackspace-email/rackspace-email-faq/index.md
Hi @catlook Could you please review and edit this PR tomorrow when you have a chance? Thank you
> Audit article: RXT email faq, changes per SME

- content/how-to/rackspace-email/migrating-from-a-pop-server-to-rackspace-email-pop-using-outlook-2010/index.md
- static/_redirects
Hiya @stephamon  Could you pleare review this PR? I'm retiring an article =)
> Retire article: Migrate form a pop server, Outlook 2010 deprecated

- content/how-to/rackspace-email/manage-domain-aliases-with-the-cloud-office-control-panel/index.md
Hi @catlook Could you please review and edit this PR when you have a chance? Thank you =)
> Audit article: Manage aliases, verbiage changes per SME

- content/how-to/cloud-servers/how-to-monitor-system-authentication-logs-in-ubuntu/index.md
New article submitted on behalf of another Racker as part of the GTS Knowledge Management project.
> New article - Monitoring system authentication

- content/how-to/rackspace-email/rackspace-webmail-chat-faq/index.md
Morning @catloook ! Could you review and edit this article when you have a chance? Thank you =)
> Audit article: Manage user spam settings, changes per SME

- content/how-to/cloud-files/why-choose-cloud-files/index.md
Changed title to be consistent with permalink. SME approved, no changes needed. 
@catlook Could you please review and edit this PR when you have a chance? Not urgent. Thank you
> Audit article: Why choose Cloud files?

- content/how-to/cloud-networks/rackconnect-v20-with-cloud-networks-faq/index.md
Good morning 🌞  @catllook ! Would you please review and edit this when you hace a chance? Thank you! 😺
> Audit article: Rackconnect v20, no changes requested by SME

- content/how-to/cloud-files/getting-started-with-cloud-files-and-cdn/index.md
:wave: @catlook ! Could you review and edit this PR please? No changes per SME, just updated Dev Guide link. Thank you
> Audit article: Getting started with CloudFiles, update RX Dev guide link

- content/how-to/cloud-servers/create-redirects-in-nginx/index.md
New article for NGINX redirects.
> Create New Article - Nginx Redirects

- content/how-to/cloud-servers/what-are-inodes-in-linux/index.md
New article submission for inodes in Linux.
> Create new article for indoes in Linux

- content/how-to/cloud-files/use-swiftly-to-upload-an-image/index.md
Hi @catlook  could you please review and edit this when you have a chance? Thank you
> Audit article: Use Swiftly to upload an image, freshened up links per SME

- content/how-to/cloud-files/set-up-a-static-website-with-cloud-files/index.md
- content/how-to/cloud-files/use-swift-to-manage-large-files/index.md
No changes per SME.
Hi @catlook , could you please review and edit this PR when you get a chance? Thank you  =)
> Audit article: Set up a static website

- content/how-to/cloud-files/use-swift-to-manage-large-files/index.md
👋🏽  @catlook could you please review and edit this PR when you have a chance? Thank you!
> Audit article: Use Swift to manage large files, no changes per SME

- content/how-to/cloud-files/use-the-api-to-manage-large-files/index.md
Hi @catlook ! Could you please review and edit this PR when you have a chance? Thank you =)
> Audit article: Use the API to..., no changes per SME

- content/how-to/cloud-servers/install-wordpress-multisite/index.md
New article about installing a multisite in Wordpress. 
Also, Wordpress configuration is unsupported at Rackspace, so can we also add some kind of disclaimer at the top of the article?
> Create article - install wordpress multisite

- content/how-to/cloud-servers/install-apache-on-debian-10/index.md
New article for how to install Apache on Debian 10.
> Create article - install apache on Debian 10.

- content/how-to/cloud-networks/create-an-isolated-cloud-network-and-attach-it-to-a-server/index.md
Hi @catlook could you please review and edit this PR when you have a chance? Thank you 😺
> Audit article: Creste an isolated Cloud network, changed last link per SME

- content/how-to/cloud-files/using-cnames-with-cloud-files-containers/index.md
Hi @catlook  Could you please review and edit this PR when you have a chance? Thank you =)
> Audit article: Set up CNname records, no changes per SME

- content/how-to/cloud-files/cloud-files-key-concepts/index.md
👋🏽  @catlook , could you please review and edit this PR when you have a chance? Than you 😸
> Audit article: Cloud files key concepts, no changes per SME

- content/how-to/cloud-servers/install-wordpress-in-centos-7/index.md
New article for installing wordpress in centos 7. 
Unsupported task. Disclaimer added near the top.
> Create article for installing wordpress in centos 7

- content/how-to/cloud-servers/linux-server-security-best-practices/index.md
Removed a typo from a command on line 365.
> Fix typo on published article

- content/how-to/rackspace-metrics/use-annotation-metrics/index.md
Hi @catlook could you please review and edit this PR when you have a chance? Thank you
> Audit article: Use annotation metrics. Change title, no changes per SME

- content/how-to/cloud-files/cloud-files-curl-cookbook/index.md
Hi Cat, can you please review and approve? Thanks!
> Audit article: cloud-files-curl-cookbook

- content/how-to/retired-articles/RETIRING-CONTENT/index.md
Hi @catlook! Could you please review and edit this PR when you have a chance? Thank you =)
> Update index.md: Fixed small typo

- content/how-to/cloud-networks/removing-networks-from-a-cloud-server/index.md
Hiya @catlook! Could you please review and edit this PR when you have a chance? Thank you 😺
> Audit article: Removing Networks...change incorrect link per SME

- content/how-to/cloud-networks/cloud-servers-attaching-and-detaching-networks/index.md
Hi @catlook Could you please review and edit this PR when you have a chance? Thank you 😺
> Audit article: Attaching and detaching networks, changes per SME

- content/how-to/cloud-networks/using-cidr-notation-in-cloud-networks/index.md
Hiya @catlook ! Could you please review and edit thisPR when you have a chance? Thank you 😺
> Audit article: Using CIDR notation..change per SME

- content/how-to/retired-articles/setup-automatic-mysql-server-backups-to-cloud-files-from-windows/index.md
- static/_redirects
Hi @catlook! Could you please review and edit this PR when you have a chance? Thank you =)
I'm retiring and redirecting an article.
> Set up automatic mysql

- content/how-to/cloud-servers/add-a-new-wordpress-user/index.md
New article to be created for how to add a wordpress user. 
Unsupported task at Rackspace, so a disclaimer was added near the top.
> create new article for adding wordpress users

- content/how-to/cloud-servers/using-fail2ban/index.md
Article submitted to assist customers with using fail2ban on a Linux server.
> Create new article for using fail2ban

- content/how-to/cloud-networks/attach-and-detach-networks-from-a-cloud-server/index.md
- static/_redirects
Hiya @stephamon ! Could you please review this redirect?
I changed the permalink and the file name, I also created a redirect.
> Change permalink, file name and create redirect

- content/how-to/cloud-servers/migrations-in-the-rackspace-cloud/index.md
Fixing a metadata issue that's currently causing a 404
> metadata fixes for 404

- content/how-to/cloud-servers/troubleshooting-sql-log-shipping/index.md
Article for troubleshooting sql log shipping in Windows.
> Create new article

- content/how-to/rackspace-email-archiving/rackspace-email-archiving-faq/index.md
Hi @catlook , Clint Fellows ( Customer Serve Technician) requested this change. 
Could you please review and edit the PR? Thank you 😺
> Update Email Archive Data export limit per Clint Fellows

- content/how-to/cloud-servers/linux-out-of-memory-killer/index.md
This article was somehow committed directly to master back in January and clearly had not been looked at by one of us. This PR does a little clean up work and formatting changes
> reformatting and edits for audit

- content/how-to/cloud-networks/basic-network-troubleshooting/index.md
Hi Cat, can you review and merge, please?
> Audit article: basic-network-troubleshooting, no changes

- content/how-to/cloud-files/cloud-files-uploading-large-files/index.md
- content/how-to/cloud-servers/troubleshoot-wordpress-refusing-an-ftp-connection/index.md
- content/how-to/cloud-servers/using-fail2ban/index.md
- content/how-to/cloud-servers/what-are-inodes-in-linux/index.md
- content/how-to/general/sin2-data-center-relocation-colocation-customer-faq/index.md
- content/how-to/general/sin2-data-center-relocation-managed-customer-faq/index.md
- content/how-to/general/sjc2-data-center-relocation/index.md
- content/how-to/rackspace-auto-scale/rackspace-auto-scale-tips-and-how-tos/index.md
- content/how-to/rackspace-monitoring/rackspace-monitoring-how-tos-and-other-resources/index.md
- content/how-to/retired-articles/object-storage-swift-in-a-rack-with-amds-seamicro-sm15000/index.md
Found a handful of articles with double quotes in the title, which are unnecessary
> removing superfluous quotation marks from metadata

- content/how-to/cloud-servers/disable-http-compression-on-apache-servers/index.md
Hiya @catlook Could you please review and edit this PR when you have a chance? Thank you
> Audit Article: Disable HTTP Compression... 

- content/how-to/cloud-servers/enable-file-downloads-in-internet-explorer/index.md
Hi @catlook Could you please review and edit this PR tomorrow, or when you have a chance? Thank you
> Audit article: Enable file downloads in Internet Explorer

- content/how-to/cloud-servers/install-mongrel-and-mongrel-clusters-on-the-ubuntu-operating-system/index.md
- static/_redirects
Hi @stephamon could you please check this PR when you have a chance 😺 ?
> Reting article: Install Mongrel.... part 1

- content/how-to/cloud-servers/copy-files-with-scp-and-rsync/index.md
Hi @catlook can you please review and approve? Thanks!
> Audit article: copy-files-with-scp..., no changes

- content/how-to/cloud-servers/using-python-novaclient-to-manage-scheduled-images/index.md
- static/_redirects
Hi @stephamon could you please review this redirect? Thank you
> Addressing permalink

- content/how-to/cloud-servers/elliptic-curve-operations/index.md
Hi @catlook, a pretty dense article... can you please review and approve?
> Audit article: elliptic-curve-operations, no changes

- content/how-to/cloud-servers/configure-apache-for-ssl-termination-on-a-cloud-load-balancer/index.md
Hi Cat, can you please review and approve?
> Audit article: configura-apache-for-ssl...-load-balancer, no changes

- content/how-to/account-management/getting-started-with-role-based-access-control-rbac/index.md
Hi @catlook could you please review and edit this when you have a chance? Thank you 😺
> Audit article: Getting started with RBAC....changes per SME

- content/how-to/cloud-servers/set-up-a-mail-relay/index.md
- content/how-to/cloud-servers/setting-up-a-mail-relay/index.md
hi @catlook, can you please review and approve? :)
> Audit article: setting-up-a-mail-relay, no changes

- content/how-to/general/definition-of-personally-identifiable-information-pii/index.md
Hi @catlook could you please review and edit this PR Monday or when you have a chance? It's not urgent, thank you.
> Audit article: Definition of personally...no changes per SME

- content/how-to/cloud-servers/design-and-build-cloud-servers-for-stability/index.md
Hi @catlook could you review and edit this Monday or when you have. chance? Thank you
> Audit article: Design and build..no changes per SME

- content/how-to/cloud-servers/system-disk-and-data-disk-faq/index.md
Hi @catlook could you please take a look at this PR Monday or when you have a chance= Thank you
> Audit article: System disk and data faq, no changes per SME

- content/how-to/cloud-files/access-cloud-files-with-transmit/index.md
New article for accessing Cloud Files from a Mac
> Create new article for accessing Cloud Files

- content/how-to/cloud-servers/hidden-base-images/index.md
Add Ubuntu 16.04 to EoL/EoS list
> Add Ubuntu 16.04 to EoL/EoS list

- content/how-to/cloud-servers/cloud-feeds-faq/index.md
Hi @catlook, when you have a chance, can you please review? Thanks. 😊
> Audit files: cloud-feeds-faq, named hrefs in the accordions

- content/how-to/managed-operations/managed-cloud-service-levels-faq/index.md
Hi @catlook, can you please review?  ☺️ Thanks!
> Audit file: managed-cloud-service-levels-faq, adds accordion

- content/how-to/retired-articles/using-python-novaclient-to-manage-scheduled-images/index.md
- static/_redirects
Hi @catlook could you review this PR? I'm retiring an article
> Retire article: Using python...part 1

- content/how-to/cloud-servers/disable-http-compression-in-apache/index.md
Hi @catlook Could you please take a look at this PR when you have a minute? Thank you
> Audit article: Disable HTTP compression...no changes per SME

- content/how-to/dedicated-hosting/manage-dns-records-in-the-myrackspace-portal/index.md
Hi @catlook could you review and edit my PR please? Thank you
> Audit article: Delete DNS Records, no changes per SME

- content/how-to/cloud-servers/speed-up-rsync-when-migrating-a-linux-server-from-the-command-line/index.md
Hi @catlook could you take a look at this PR when you have a chance? Thank you 😺
> Audit article: Speed up Rsync..no changes per SME

- content/how-to/cloud-servers/sophos-error-on-EOL-Windows-Server-2008/index.md
> Create new article - Sophos error on EOL Windows server

- content/how-to/cloud-servers/slow-windows-login/index.md
Hi @catlook could you please review and edit this PR monday when you have a chance? Thank you
> Slow windows logins

- content/how-to/cloud-servers/check-database-for-corruption/index.md
> Create new article - Check Database corruption

- content/how-to/domain-redirect-types/index.md
> Create new article - Domain redirect types

- content/how-to/cloud-servers/enable-SSL-and-remote-connections-for-mysql/index.md
New article submitted by FLR for creation.
> Create new article - Enable SSL and remote connections for MySQL

- content/how-to/cloud-servers/investigate-a-compromised-windows-server/index.md
> Create new article - Investigate Compromised Windows Server

- content/how-to/cloud-files/cloud-files-faq/index.md
Hi @catlook could you please review and edit this PR when you have a chance? Thank you 😺
> Audit article: Cloud Files FAQ, no changes per SME

- content/how-to/cloud-servers/upgrade-apache-http-server-2.2-to-2.4-in-rhel-and-centos/index.md
Change article's title and delete reference to RHEL/CentOS6 per SME.
Hi @catlook could you please review and edit this when you have a chance? Thank you
> Modify article, delete reference to RHEL/CentOS6 per SME

- content/how-to/cloud-servers/create-a-sudo-user-in-ubuntu/index.md
Hi @catlook, can you please review? Thanks! ☺️
> Audit articles: create-a-sudo-user-in-ubuntu, no changes

- content/how-to/cloud-files/cloud-files-streaming-simple-flash-files/index.md
- content/how-to/cloud-files/stream-simple-flash-files-from-cloud-files/index.md
Hi @catlook, can you please review? The whole article is about flash, which is being discontinued everywhere except China, should this be archived? Thanks!
> Audit files: cloud-files-streaming-simple-flash-files, adds Disclaimer

- content/how-to/cloud-networks/rackspace-neutron-based-networking-api-faq/index.md
HI @catlook could you review and edit this PR when you have a chance? Thank you
> Audit article: Rackspace Neutron based..changes per SME

- content/how-to/cloud-networks/attach-a-cloud-network-to-an-existing-cloud-server/index.md
Hi @catlook could you please review this PR on Monday? Thank you
> Audit article: attach-a-cloud-network, change per SME

- content/how-to/cloud-files/streaming-cloud-files-with-jw-player/index.md
Hi @catlook, can you please review? ☺️ Thanks!
> Audit files: streaming-cloud-files-with-jw-player, adds Disclaimer

- content/how-to/cloud-servers/how-to-enable-SSL-TLS-perfect-forward-secrecy/index.md
New article for creation submitted by FLR.
> Create new article - Perfect Forward Secrecy

- content/how-to/cloud-files/cloud-files-streaming-with-osmf-plugins/index.md
Hi @catlook, can you please review? another file referencing flash players. Thanks! 😊
> Audit files: cloud-files-streaming-with-osmf-plugins, adds Disclaimer

- content/how-to/cloud-servers/transport-layer-security-registry-settings/index.md
> Create new article - TLS registry settings

- content/how-to/rackspace-intelligence/_index.md
Hi @catlook, can you please review when you have a chance? 😊 Thanks!
> Audit article: rackspace-intelligence, removes 404 link

- content/how-to/cloud-dns/rackspace-cloud-dns-api-example/index.md
Hi @catlook, can you please review? Thanks 😊.
> Audit article: rackspace-cloud-dns-api-example, no changes

- content/how-to/retired-articles/getting-started-with-apache-hadoop-on-rackspace-cloud/index.md
- static/_redirects
Hi @catlook. This is a retired article.
> Retires article: getting-started-with-apache-hadoop-on-rackspace-cloud

- content/how-to/general/support/index.md
> number-update

- content/how-to/cloud-servers/prevent-issues-with-windows-server-reboots/index.md
> command rectification

- content/how-to/general/legal/index.md
Hi @catlook, can you please review when you have a chance? Thanks! 😊
> Audit changes legal, Rackspace changes to Rackspace Technology

- content/how-to/cloud-files/use-swift-to-manage-large-files/index.md
- content/how-to/cloud-files/use-swiftly-to-upload-an-image/index.md
- content/how-to/cloud-files/use-the-api-to-manage-large-files/index.md
Same changes to the last 3 files. Hi @catlook, can you please review and see if it is ok? thanks in advance ☺️.
> changes feedback message part 2

- content/how-to/cloud-databases/use-ssl-with-your-cloud-database-instance/index.md
- static/_redirects
name changes to use-ssl-with-your-cloud-database-instance, changes link to .pem file, static/_redirects modifies accordingly. Hi @catlook, can you please review when you have a chance? Thanks! ☺️
> Audit article: using-ssl-with-your-cloud-database-instance:

- content/how-to/retired-articles/object-storage-swift-in-a-rack-with-amds-seamicro-sm15000/index.md
Putting these double quotes back in to fix the O365 app pipeline
> fixing some issues

- content/how-to/dedicated-hosting/windows-spheres-of-support-for-dedicated-and-managed-ops/index.md
Updated document to reflect our support for SQL 2019
> Add SQL 2019 Support 

- content/how-to/managed-operations/choosing-between-rdbms-and-nosql/index.md
Hi @catlook, can you please review? Thanks!c😊
> Audit article: choosing-between-rdbms-and-nosql, no changes

- content/how-to/managed-operations/introduction-to-cassandra/index.md
Hi @catlook, can you please review? Thanks! 😊
> Audit articles: introduction-to-cassandra, no changes

- content/how-to/managed-operations/intro-to-databases-intro/index.md
Hi @catlook, can you please review? Thanks!😊
> Audit article: intro-to-databases-intro, no changes

- content/how-to/managed-operations/introduction-to-mongodb/index.md
Hi @catlook, can you please review? Thanks! ☺️
> Audit file: introduction-to-mongodb, adds registered trademarks

- content/how-to/managed-operations/reasons-to-use-an-sql-database/index.md
Hi @catlook, can you please review? Thanks! ☺️
> Audit article: reasons-to-use-an-sql-database, fixes broken link

- content/how-to/managed-operations/reasons-to-use-a-nosql-database/index.md
Hi @catlook, can you please review? Thanks! 😊
> Audit article: reasons-to-use-a-nosql-database, no changes

- content/how-to/managed-operations/types-of-databases/index.md
Hi @catlook, can you please review? Thanks! ☺️
> Audit article: types-of-databases, no changes

- content/how-to/cloud-servers/use-sftp-and-scp/index.md
- content/how-to/cloud-servers/using-sftp-and-scp/index.md
New how-to. Hi @catlook, can you please review when you can? Thanks! 😊
> Toosalgadopatch1: using-sftp-and-scp

- content/how-to/dedicated-hosting/add-cpu-to-server-or-hypervisor/index.md
- content/how-to/dedicated-hosting/add-disk-space-to-server-or-hypervisor/index.md
- content/how-to/dedicated-hosting/add-new-vpn-user-myrackspace-portal/index.md
- content/how-to/dedicated-hosting/add-ram-to-server-or-hypervisor/index.md
- content/how-to/dedicated-hosting/check-bandwidth-usage/index.md
- content/how-to/dedicated-hosting/create-new-user-on-active-directory-domain/index.md
- content/how-to/dedicated-hosting/delete-an-object-group-with-firewall-manager-v2/index.md
- content/how-to/dedicated-hosting/delete-vpn-user-myrackspace-portal/index.md
- content/how-to/dedicated-hosting/firewall-manager-v2/index.md
- content/how-to/dedicated-hosting/how-to-request-a-csr/index.md
- content/how-to/dedicated-hosting/id-federation-map-policies-permissions-dedicated/index.md
- content/how-to/dedicated-hosting/manage-local-users-in-the-myrackspace-portal/index.md
- content/how-to/dedicated-hosting/manage-user-permissions-for-dedicated-hosting/index.md
- content/how-to/dedicated-hosting/modify-an-object-group-with-firewall-manager-v2/index.md
- content/how-to/dedicated-hosting/request-additional-ip-addresses/index.md
- content/how-to/dedicated-hosting/reset-user-password-on-active-directory-domain/index.md
- content/how-to/dedicated-hosting/reset-your-cisco-asa-vpn-user-password-by-using-the-rackspace-portal/index.md
- content/how-to/dedicated-hosting/view-an-object-group-with-firewall-manager-v2/index.md
- content/how-to/dedicated-hosting/view-your-network-device-configuration/index.md
Fix the drop-down name, changing it to "Rackspace Dedicated". Applied a bunch of other edits as needed.
> apply fixes

- content/how-to/general/remediation-of-cve-2021-34527-windows-print-spooler-remote-code-execution-vulnerability/index.md
Add article for remediations for MS vulnerability
> add content for ms vulnerability

- content/how-to/cloud-servers/too-many-connections-error-in-mysql/index.md
- content/how-to/cloud-servers/too-many-connections-in-mysql/index.md
> Create new article - too many connection in mysql

- content/how-to/managed-operations/adding-a-managed-operations-service-level-to-your-cloud-account/index.md
Hiya @catlook! Could you please review and edit this when you get a chance? Thank you =)
> Updated article, and fixed 404 link per Z McCroklyn's request

- content/how-to/cloud-images/pitchfork-for-cloud-images/index.md
Hello! I noticed this article has some errors. Such as an extra "]" and the wrong usage of a code block.
> Fix some syntax errors 

- content/how-to/rackconnect/rackconnect-global-faq/index.md
Hi @catlook Could you please review and update this PR when you have a chance? Thanks!
> Update RackConnect Global FAQ article per Peter Gilani

- content/how-to/managed-operations/adding-a-managed-operations-service-level-to-your-cloud-account/index.md
Remove bad links to pricing information
> update pricing info

- content/how-to/cloud-servers/cors-errors/index.md
> CORS Errors - Article

- content/how-to/cloud-servers/basic-nginx-troubleshooting/index.md
> Basic Nginx troubleshooting - Article

- content/how-to/cloud-servers/php-errors/index.md
> PHP Errors - Article

- content/how-to/cloud-servers/regex-cheat-sheet-basics/index.md
> Regex Cheat Sheet/Basics - Article

- content/how-to/cloud-servers/index.md
> Receiving 403 error in a website - Article

- content/how-to/cloud-servers/restore-a-single-table-from-a-full-mysqldump-file/index.md
> Restore a single table MySQL - Article

- content/how-to/cloud-servers/create-remove-swap-file-in-ubuntu/index.md
> Fix swapfile path in removal instructions

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Added support for Oracle Linux 7 and Oracle Linux 8 for the FAWS and Azure platform
> Oracle Linux 7 and 8 Support

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Added Support for Podman in RHEL8
> Support for Podman

- content/how-to/cloud-servers/use-find-and-locate-to-search-for-files-in-linux/index.md
> Article - Find and Locate to search for files

- content/how-to/cloud-servers/updating-apache-to-the-latest-version-in-linux/index.md
> Article - Updating Apache to the Latest Version

- content/how-to/cloud-servers/installing-apache-on-fedora-31/index.md
> Article - Installing Apache on Fedora 31

- content/how-to/cloud-servers/setup-name-based-virtual-host-in-apache/index.md
> Article - Setup a Name-Based VHost in Apache

- content/how-to/cloud-servers/checking-your-network-connections-on-Linux/index.md
> Article - Checking Network Connections on Linux

- content/how-to/cloud-servers/enable-php-curl-on-a-ubuntu-LAMP-stack/index.md
> Article - Enable curl in PHP on ubuntu

- content/how-to/cloud-servers/differences-between-hardware-and-software-firewalls/index.md
> Article - Hardware and Software Firewalls

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Adding Support for AlmaLinux 8 and Rocky Linux 8
> Adding Support for AlmaLinux 8 and Rocky Linux 8

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Added Support for AlmaLinux 8, Rocky Linux 8, & Debian 11 for Public Cloud Platforms
> Updates to AlmaLinux 8, Rocky Linux 8, Debian 11

- content/how-to/rackspace-fabric/common-request-templates/index.md
Jira: https://rackspace.atlassian.net/browse/PLATEXP-398
- This adds a product/service column to the table since it is another field that plays a factor in revealing a template.
- Minor corrections and cleanup found along the way
This was referenced against each template code in https://github.rackspace.com/bpit/templates/tree/master/db/templates
> Add product column to table

- content/how-to/rackspace-email-open-xchange-faq/index.md
- content/how-to/rackspace-email/open-xchange-faq/index.md
Adding a new page as a FAQ that will be referenced in a communication to be sent to the Rackspace Email installed base. This FAQ answers questions about what features are changing to become compatible with our future Open-Xchange platform.
> Creating Open-Xchange FAQ page

- content/how-to/cloud-servers/set-up-lsyncd-locally-and-over-ssh-to-sync-directories/index.md
> Article - Set up Lsyncd

- content/how-to/cloud-servers/managing-duplicate-cron-jobs/index.md
> Article - Managing cron jobs

- content/how-to/rackspace-email/open-xchange-faq/index.md
Updated the 2nd paragraph and removed 'forward & delete' from the removed list.
> Updated OX FAQ

- content/how-to/rackspace-email/open-xchange-faq/index.md
- content/how-to/rackspace-email/set-an-email-catch-all-address/index.md
- content/how-to/rackspace-email/set-up-rackspace-email-forwarding/index.md
- content/how-to/rackspace-email/split-domain-routing/index.md
Updated the OX FAQ.  Removed the CP steps from the document that explains how to setup a forward address. Added a note to the Catch all, and SDR documents informing people that it has been sunset.
> Several document updates for OX

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Debian 9 EOL and Various Placeholders for new OSes
> Debian 9 EOL and Various Placeholders for new OSes

- content/how-to/rackspace-fabric/azure-v2-upgrade/index.md
JIRA: https://rackspace.atlassian.net/browse/PLATEXP-1238
Fixes typo for broken image src so it displays
> Fix edit group image name

- content/how-to/rackspace-email/open-xchange-faq/index.md
Updated the IMAP, POP, SMTP server and port faq
> Updated the IMAP,POP, SMTP FAQ

- content/how-to/rackspace-email/disable-insecure-access/index.md
Created a new article for insecure access
> New article for insecure access

- content/how-to/account-management/change-account-information/index.md
This is the second trial for the same document.
> DEXP-1590 Change Account Information 

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Added RSVC
Renamed Platform names
> OS and Platform Updates

- content/how-to/office-365/_index.md
- content/how-to/office-365/how-to-set-up-O365-via-your-cloud-office-control-panel/index.md
https://rackspace.atlassian.net/browse/PLATEXP-2626
> PLATEXP-2626: How to set up O365 via your cloud office control panel

- content/how-to/office-365/how-to-set-up-O365-via-your-cloud-office-control-panel/index.md
https://rackspace.atlassian.net/browse/PLATEXP-2626
> Additional corrections from stakeholders

- content/how-to/rackspace-email/manage-cloud-office-administrator-information-in-the-control-panel/index.md
> Updates from Chris Phillips

- static/_redirects
Configuring to Configure for Cloud Files with Cyberduck
> Adding redirect

- content/how-to/dedicated-hosting/linux-spheres-of-support-for-dedicated-and-managed-ops/index.md
Removed Ubuntu 18.04 LTS
Added Debian 12
Updated Ubuntu 22.04 LTS
> Update to Spheres of Support July 2023
